client_id = "-SS1000-1oyBU14WbzdF"
client_port = 6681
lifetime_downloaded = 86126633164
lifetime_uploaded = 1943961600
private_client = false
torrent_sort_column = "Up"
torrent_sort_direction = "Descending"
peer_sort_column = "UL"
peer_sort_direction = "Descending"
ui_theme = "catppuccin_mocha"
default_download_folder = "/home/rushi/Downloads"
max_connected_peers = 2000
bootstrap_nodes = [
    "router.utorrent.com:6881",
    "router.bittorrent.com:6881",
    "dht.transmissionbt.com:6881",
    "dht.libtorrent.org:25401",
    "router.cococorp.de:6881",
]
global_download_limit_bps = 0
global_upload_limit_bps = 0
max_concurrent_validations = 64
connection_attempt_permits = 50
upload_slots = 8
peer_upload_in_flight_limit = 4
tracker_fallback_interval_secs = 1800
client_leeching_fallback_interval_secs = 60
output_status_interval = 0

[[torrents]]
torrent_or_magnet = "magnet:?xt=urn:btih:06911509C0AFC47986CD9988CE9E793D05A424EF&dn=F1+22%3A+Champions+Edition+%28Denuvoless+v1.05+%2B+5+DLCs%2C+MULTi11%29+%5BFitGirl+Repack%2C+Selective+Download+-+from+23.3+GB%5D&tr=udp%3A%2F%2Fopentor.org%3A2710&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=http%3A%2F%2Ftracker.dler.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=udp%3A%2F%2Fipv4.tracker.harry.lu%3A80%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Fretracker.lanta-net.ru%3A2710%2Fannounce&tr=udp%3A%2F%2Ftracker.cyberia.is%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.moeking.me%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.tiny-vps.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=udp%3A%2F%2Fopentor.net%3A6969&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=http%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&tr=udp%3A%2F%2Fopentracker.i2p.rocks%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.internetwarriors.net%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fcoppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.zer0day.to%3A1337%2Fannounce"
name = "F1 22 [FitGirl Repack]"
validation_status = true
download_path = "/home/rushi/Downloads"
container_name = "F1 22 [FitGirl Repack] [06911509c0afc47986cd9988ce9e793d05a424ef]"
torrent_control_state = "Running"

[torrents.file_priorities]

[rss]
enabled = true
poll_interval_secs = 900
max_preview_items = 500
feeds = []
filters = []
