---
runtime:
  threads: ~
  networkSecurity: safe
release:
  check: true
manifest:
  enable: true
  secondary:
    - url: " https://raw.githubusercontent.com/BloodShed-Oni/ludusavi-extra-manifests/main/BS_ex-manifest.yaml"
      enable: true
language: en-US
theme: dark
roots:
  - store: steam
    path: /home/rushi/.local/share/Steam/
  - store: otherWine
    path: /home/rushi/.local/share/Steam/steamapps/compatdata/*/pfx/
  - store: steam
    path: /mnt/Data/SteamLibrary/
  - store: otherWine
    path: /mnt/Data/SteamLibrary/steamapps/compatdata/*/pfx/
  - store: heroic
    path: /home/rushi/.config/heroic
  - store: otherWine
    path: /mnt/Data/Games/Heroic/Prefixes/default/*/
  - store: lutris
    path: /home/rushi/.local/share/lutris
    database: /home/rushi/.local/share/lutris/pga.db
  - store: otherWine
    path: /mnt/Data/Games/.itch/*/pfx/
redirects: []
backup:
  path: /home/rushi/.game-saves
  ignoredGames: []
  filter:
    excludeStoreScreenshots: false
    cloud:
      exclude: false
      epic: false
      gog: false
      origin: false
      steam: false
      uplay: false
    ignoredPaths: []
    ignoredRegistry: []
  toggledPaths: {}
  toggledRegistry: {}
  sort:
    key: name
    reversed: false
  retention:
    full: 1
    differential: 0
  format:
    chosen: zip
    zip:
      compression: zstd
    compression:
      deflate:
        level: 6
      bzip2:
        level: 6
      zstd:
        level: 10
  onlyConstructive: false
restore:
  path: /home/rushi/ludusavi-backup
  ignoredGames: []
  toggledPaths: {}
  toggledRegistry: {}
  sort:
    key: status
    reversed: false
  reverseRedirects: false
scan:
  showDeselectedGames: true
  showUnchangedGames: true
  showUnscannedGames: true
cloud:
  remote: ~
  path: ludusavi-backup
  synchronize: true
apps:
  rclone:
    path: /usr/bin/rclone
    arguments: "--fast-list --ignore-checksum"
customGames: []
