[General]
bookmarks=/home/rushi
lastDisplay=0
maximizedWindow=false
placesPanel=true
savedPaths=/home/rushi, /home/rushi/Desktop, /home/rushi/Documents, /home/rushi/Downloads, /home/rushi/Games, /home/rushi/go, /home/rushi/Music, /home/rushi/Pictures, /home/rushi/PortProton
windowGeometry=@Rect(0 0 938 1024)
